### ISSUE TITLE
Future Development: Global stylesheet to assets

### ISSUE THREAD

**Issue by leavinit** [adj-dev/prota#79]
Unifying styles across components will greatly ease future changes to the look and feel of the site's funtionality

**Comment by adj-dev** [comment]
I've made major changes to CSS structure, and as of now I am content with how it stands. My first impulse was to add all styles to a single file in assets, but after creating a file with all styles I found it to be too bulky. I compromised between a single, global CSS file and a purely modularized structure. As it is currently we have more of a hybrid structure where styles that are unique to a components are contained in a modular file in the same folder as the component, and shared styles are located in the nearest common ancestors folder.

**Comment by adj-dev** [comment]
I'll give you the ability to review the changes I've made and decide whether this issue should be closed.

**Comment by leavinit** [comment]
Sounds Good.  I like the idea you settled on and will likely close the issue fairly quickly.

**Comment by leavinit** [comment]
Closing the issue.  That principle (shared styles stick with the common ancestor) is a tidy way to keep track of things.  Your code comments help a lot as well.  Coding with the idea in mind that other people might have to be working with it in the future will keep us streamlined.  Keep up the good work!
